### ISSUE TITLE
Graph view

### ISSUE THREAD

**Issue by LeoDroidCoder** [kaygisiz/Dependency-Graph-Plugin#10]
Thank you for the effort.
Is there any other representation? 
Current view seems really useless. 
It's impossible to figure something out there

**Comment by kaygisiz** [comment]
This project just converts existed library to android studio plugin, if you want to see changes about generating and displaying graph you can check out to [this project](https://github.com/alexzaitsev/apk-dependency-graph).

And yes i couldn't find another library or something else too.
